Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,19 +1,13 @@
 name: Deploy to ECR
-# updated ECR Repo week3-1 01/22
-on: 
+on:
   push:
     branches: [ master ]
 
 jobs:
-  
   build:
-    
-    name: Build Image
     runs-on: ubuntu-latest
 
-   
     steps:
-
     - name: Check out code
       uses: actions/checkout@v4
 
@@ -26,6 +20,11 @@ jobs:
         AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
         AWS_REGION: us-east-1
 
+    - name: Debug ECR Registry
+      run: echo "ECR_REGISTRY is $ECR_REGISTRY"
+      env:
+        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+
     - name: Build, test, tag, and push image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -34,12 +33,10 @@ jobs:
       run: |
         cd Chapter02/kubia/
         ls -ltra
-        # Docker build command
-        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-        # Unit test
-        docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --progress=plain
+        docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || (echo "Run failed"; docker logs nodeapp; exit 1)
         docker ps
         echo "Pause for 10 seconds to let container start"
         sleep 10
-        curl localhost -vvv
+        curl localhost:80 -vvv || (echo "Curl failed"; exit 1)
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
